using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TEWTools
{
    public class Attributes
    {
        public int WorkerUID { get; set; }
        public int Attribute { get; set; }
        public bool Hidden { get; set; }

        public Dictionary<int, string> AttributeName = new Dictionary<int, string>(){
            {1, "Professional"},
            {2, "Quiet"},
            {3, "Stalwart"},
            {4, "Relaxed"},
            {5, "Lively"},
            {6, "Class Clown"},
            {7, "Party Animal"},
            {8,"People Person"},
            {9, "Irrepressible"},
            {10, "Free Spirit"},
            {11, "Driven"},
            {12, "Intense"},
            {13, "Mercenary"},
            {14, "Loner"},
            {15, "Prickly"},
            {16, "Selfish"},
            {17, "Gloomy"},
            {18, "Insecure"},
            {19, "Needy"},
            {20, "Sleazy"},
            {21, "Troublemaker"},
            {22, "Agitator"},
            {23, "Egomaniac"},
            {24, "Unpredictable"},
            {25, "Grifter"},
            {26, "Bully"},
            {27, "Wild"},
            {28, "Scumbag"},
            {100, "Highly Moral"},
            {101, "Unfaithful"},
            {102, "Horndog"},
            {103, "Creative Dynamo"},
            {104, "Very Creative"},
            {105, "Creative"},
            {106, "Passes On Knowledge"},
            {107, "Unapproachable"},
            {108, "Highly Strung"},
            {109, "Positive Outlook"},
            {110, "Thin Skinned"},
            {111, "Notorious Ribber"},
            {112, "Anti-Hardcore"},
            {113, "Keeps Kayfabe"},
            {114, "Extremely Old School"},
            {115, "Money Motivated"},
            {116, "Loves The Business"},
            {117, "Fame Hungry"},
            {118, "Has A Temper"},
            {119, "Born Fighter"},
            {120, "Bad Ass Reputation"},
            {121, "Motormouth"},
            {122, "Story Teller"},
            {123, "Prudish" },
            {124, "Apolitical"},
            {125, "Easy To Do Business With"},
            {126, "Business Mindset"},
            {127, "Political Player"},
            {128, "Control Freak"},
            {129, "Faithful"},
            {130, "Desireless"},
            {131, "Talent Spotter"},
            {132, "That Doesn't Work For Me, Brother"},
            {133, "It's Who You Know"},
            {197, "Chequered Past"},
            {198, "Often In Trouble"},
            {199, "Most Wanted"},
            {201, "Former Smoker"},
            {202, "Smoker"},
            {203, "Heavy Smoker"},
            {204, "Former Drinker"},
            {205, "Drinker"},
            {206, "Heavy Drinker"},
            {207, "Former Soft Drug User"},
            {208, "Soft Drug User"},
            {209, "Heavy Soft Drug User"},
            {210, "Former Hard Drug User"},
            {211, "Hard Drug User"},
            {212, "Heavy Hard Drug User"},
            {213, "Former Steroid User"},
            {214, "Steroid User"},
            {215, "Heavy Steroid User"},
            {216, "Former Pain Killer Abuser"},
            {217, "Pain Killer Abuser"},
            {218, "Heavy Pain Killer Abuser"},
            {219, "Straight Edge"},
            {225, "Movie Star"},
            {226, "TV Actor"},
            {227, "Famous Musician"},
            {228, "Musician"},
            {229, "MMA Fighter"},
            {230, "Former MMA Fighter"},
            {231, "Stud Athlete"},
            {232, "Gymnastic Background"},
            {233, "Boxer"},
            {234, "Former Boxer"},
            {235, "Pro Martial Artist"},
            {236, "Former Pro Martial Artist"},
            {301, "Daredevil"},
            {302, "Fearless"},
            {303, "Risk Taker"},
            {304, "Stuntman"},
            {305, "No Stunts"},
            {306, "Deathmatch Wrestler"},
            {307, "Will Risk Injury"},
            {310, "100% Babyface"},
            {311, "Better As Babyface"},
            {312, "Better As Heel"},
            {313, "100% Heel"},
            {314, "Amazing Babyface"},
            {315, "Amazing Heel"},
            {320, "Plays Dominant Well"},
            {321, "Plays Comedy Well"},
            {322, "Plays Swagger Well"},
            {323, "Plays Gimmicky/Cartoonish Well"},
            {324, "Plays Bad Ass Well"},
            {325, "Plays Legitimate Well"},
            {326, "Plays Weasley/Underdog Well"},
            {327, "Plays Realistic Well"},
            {328, "Plays Mysterious/Occult Well"},
            {329, "Plays Offbeat/Unstable Well"},
            {330, "Can't Play Dominant"},
            {331, "Can't play Comedy"},
            {332, "Can't Play Swagger"},
            {333, "Can't Play Gimmicky/Cartoonish"},
            {334, "Can't Play Bad Ass"},
            {335, "Can't Play Legitimate"},
            {336, "Can't Play Weasely/Underdog"},
            {337, "Can't Play Realistic"},
            {338, "Can't Play Mysterious Occult"},
            {339, "Can't Play Offbeat/Unstable"},
            {340, "No Comedy Matches"},
            {341, "Poor Comedy Matches"},
            {342, "Noted Comedy Match Performer"},
            {343, "Comedy Match Worker"},
            {344, "Canny Operator"},
            {345, "Dynamo"},
            {346, "Tag Team Specialist"},
            {347, "Selfish Performer"},
            {348, "Giving Performer"},
            {349, "Explosive Ring Style"},
            {350, "Squash Master"},
            {351, "Scatterbrained"},
            {352, "High Pain Threshold"},
            {353, "Slow And Steady"},
            {356, "Voice of Epics"},
            {357, "Voice of Stories"},
            {358, "Voice of Chaos"},
            {359, "Voice of Comedy"},
            {360, "Voice of Sleaze"},
            {361, "Agent Of The Old School"},
            {362, "Agent Of Tag Teams"},
            {363, "Agent Of Rumbles"},
            {364, "Agent Of Epics"},
            {365, "Agent Of Stories"},
            {366, "Agent Of Chaos"},
            {367, "Agent Of Comedy"},
            {368, "Notable Referee"},
            {369, "Definitive Style"},
            {501, "Natural Trainer"},
            {502, "Desperado"},
            {503, "Heavy Social Media User"},
            {504, "Shuns Social Media"},
            {505, "Healing Factor"},
            {506, "Career Woman"},
            {507, "Prodigy"},
            {508, "Not A Natural"},
            {509, "Age Is Just A Number"},
            {510, "Can't Fight Time"},
            {511, "Ahead Of Their Time"},
            {512, "Homebody"},
            {513, "World Traveler"},
            {514, "Deep Roots"},
            {515, "Fitness Fanatic"},
            {516, "Bodybuilder"},
            {517, "Skinny Genes"},
            {518, "Fat Genes"},
            {519, "Masked For Life"},
            {520, "Troublesome Neck"},
            {521, "Troublesome Back"},
            {522, "Troublesome Shoulder"},
            {523, "Troublesome Knee"},
            {524, "History Of Concussions"},
            {525, "Loyal"},
            {526, "Itchy Feet"},
            {527, "Future Referee"},
            {528, "Future Announcer"},
            {529, "Future Colour Commentator"},
            {530, "Future Manager"},
            {531, "Future Personality"},
            {532, "Future Road Agent"},
            {533, "Wrestling In The Blood"},
            {534, "Outside Interests"},
            {535, "Modelling Experience"},
            {536, "Hot New Move"},
            {537, "Hot New Catchphrase"},
            {538, "Flavour Of The Month"},
            {539, "Personal Issues"},
            {540, "Groundswell Of Support"},
            {541, "Midas Touch"},
            {542, "In A Funk"},
            {543, "Unable To Wrestle Again"},
            {544, "Speech Impediment"},
            {545, "A Marketing Nightmare"},
            {546, "Unmarketable"},
            {547, "Easily Marketable"},
            {548, "A Marketing Dream"},
            {549, "No Pregnancies"},
            {550, "Golden Mane"},
            {551, "Life Long Underdog"}
        };
    }
}
